title: 2018 Alberta Mixed Reality Workshop
description: An Albertan workshop for academics and industry partners exploring Mixed Reality.
sitename: 2018 Alberta Mixed Reality Workshop
baseurl: '/alberta-mr-workshop-2018'
sass:
  sass_dir: /assets/_sass
  style: :compressed
collections:
  - features
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE.txt
  - CNAME